[workspace]
members = [
    "crates/core",
    "crates/domain",
    "crates/infra-core",
    "crates/infra-process",
    "crates/infra-ipc",
    "crates/infra-vision",
    "crates/infra-device",
    "crates/infra-script",
    "crates/app",
    "crates/api",
    "crates/main",
]
resolver = "2"

[workspace.dependencies]
# 异步/序列化
tokio = { version = "1", features = ["full"] }
async-trait = "0.1.89"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
bincode = "2.0.1"
#erased-serde = "0.4.6"

#日志
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
#anyhow = "1.0"
thiserror = "1.0"
uuid = { version = "1.0", features = ["v4", "serde"] }
#fs_extra = "1.3"
#once_cell = "1.21"
#log = "0.4.27"

# Tauri相关
tauri = { version = "2.0", features = ["uuid", "unstable"] }
tauri-plugin-opener = "2.0"
tauri-build = { version = "2.0", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-notification = "2"
tauri-plugin-store = "2"
tauri-plugin-autostart = "2"
tauri-plugin-global-shortcut = "2"
tauri-plugin-window-state = "2"

# 视觉和AI相关
xcap = "0.7"
#ort = { version = "2.0.0-rc.4", features = ["load-dynamic"] }
ort = { version = "2.0.0-rc.4", features = ["directml", "cuda"] }
image = { version = "0.25", features = ["png", "jpeg", "bmp"] }
base64 = "0.22"
ndarray = "0.16"
imageproc = "0.25.0"
##绘制/更改为前端绘制检测结果
#raqote = { version = "0.8", default-features = false,  features = ["text"] }
#font-kit = { version = "0.14"}
rayon = "1.11.0"

# 系统相关
num_cpus = "1.16"
core_affinity = "0.8"
#sysinfo = "0.37"
memmap2 = "0.9"
interprocess = { version = "2.2.3", features = ["tokio"] }

# 时间和配置
chrono = { version = "0.4", features = ["serde"] }
cron = "0.15.0"

# 哈希
ahash = "0.8.12"
#twox-hash = { version = "2.1.1", features = ["xxhash3_64"] }
sha3 = "0.10.8"

#设备
adb_client = "2.1.17"

# 表达式
rhai = "1.23.4"
which = "8.0.0"

# 平台特定依赖
winapi = { version = "0.3", features = ["winuser", "processthreadsapi", "handleapi"] }
windows = { version = "0.62.2", features = [
    "Win32_Foundation",
    "Win32_System_ProcessStatus",
    "Win32_System_Threading",
    "Win32_Security",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Memory",
    "Win32_System_SystemInformation",
    "Win32_Graphics_Gdi",
] }
libc = "0.2.177"
nix = "0.30"